export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const DELETE_TODO = 'DELETE_TODO';
export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';

export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'REGISTER_USER';
